### PR TITLE
Created Peerunity Theme.  Contains new icons, modification to global

### PR DESCRIPTION
**Pull request by SigmundAlpha**
color constants, and some edits to bitcoingui.ccp to load the
stylesheets and new fonts.  Packaged with WeblySleek UI Normal font and
Font Awesome icons.

Updated QSS and Changed Toolbar Properties

Updating Overview Page

Finished OverviewPage, changed some icons.

Packaged and applied a global font. Started on Sendcoinsdialog

More icon replacements, skin tables, and more controls.

### CODE REVIEW

**Comment by brossi** [comment]
@SigmundAlpha , awesome work! I'm going to work with the team to release 0.1.2 in the next day, and then I'll open up a new 0.1.3-RC1 branch that has the new theme integrated into it. Presuming that the testing goes as expected, 0.1.3 will be released very soon after that.

**Comment by CoinGame** [comment]
Wow this looks really good. I love it.

**Comment by SigmundAlpha** [comment]
@brossi glad you like it.

**Comment by brossi** [comment]
Leave it open for now. It will need to be merged against master

**Comment by sandakersmann** [comment]
Very nice :+1:

**Comment by glv2** [comment]
Merged in commit 135d683fec6058f9b9056e90eee73431020171e4

**Pull request closed without merging**
