### PR TITLE
Fix for #153

### PR DESCRIPTION
**Pull request by emeth-**

### CODE REVIEW

**Comment by emeth-** [comment]
Currently signrawtransaction throws error if wallet is encrypted, regardless of whether it's locked or unlocked. Relax error message to only be thrown when wallet is locked.

**Comment by emeth-** [comment]
Updated as per your suggestion Sunny. Makes sense.

**Comment by sunnyking** [comment]
emeth, could you squash these 2 commits before going in, I think it's good now (glv2 okayed it as well).

**Comment by emeth-** [comment]
Done

**Pull request merged**
